server:
  port: 8761

eureka:
  environment: dev
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
    register-with-eureka: false #关闭自己作为客户端注册
    fetch-registry: false

#用户名和密码，等会访问的时候，会要求你登录，服务注册的时候也需要带着用户名和密码
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456